logging.file: logs/application.log
#logging:
#  level:
#      org:
#        springframework:
#          web: DEBUG
#        hibernate: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:./h2/org;MODE=MySQL
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
